import type { Source } from "./types";
export const REFRESH_MINUTES = 15;
export const DEFAULT_NEWS_DAYS = "7";
export const sources: Source[] = [
  {
    id: "ia",
    name: "هيئة التأمين",
    url: "https://www.ia.gov.sa/ar/home",
    type: "official",
    connector: "ia",
    note: "قراءة الصفحة العامة للأخبار؛ مع احترام سياسة الوصول.",
  },
  {
    id: "cma",
    name: "هيئة السوق المالية",
    url: "https://cma.gov.sa/MediaCenter/NEWS/Pages/default.aspx",
    type: "official",
    connector: "cma",
    note: "الأخبار والإعلانات الرسمية المنشورة للعامة.",
  },
  {
    id: "saudire",
    name: "السعودية لإعادة التأمين",
    url: "https://saudire.net/",
    type: "official",
    connector: "rss",
    feedUrl: "https://saudire.net/ar/feed/",
    category: "sector",
    note: "تغذية RSS العربية المعلنة في الموقع الرسمي؛ تاريخ آخر إعلان قد يكون أقدم من نافذة العرض المختارة.",
  },
  {
    id: "najm",
    name: "نجم لخدمات التأمين",
    url: "https://najm.sa/",
    type: "official",
    note: "غير مربوط؛ أعاد الموقع HTTP 403 عند اختبار الجلب. يلزم وصول مصرح به من نجم.",
  },
  {
    id: "sama",
    name: "البنك المركزي السعودي",
    url: "https://www.sama.gov.sa/",
    type: "official",
    note: "غير مربوط؛ مسارات الأخبار المختبرة أعادت 404، وrobots.txt أعاد صفحة HTML بدل سياسة وصول. يلزم رابط تغذية رسمي صالح.",
  },
  {
    id: "exchange",
    name: "تداول السعودية",
    url: "https://www.saudiexchange.sa/",
    type: "official",
    note: "غير مربوط؛ أعاد الموقع HTTP 403 من الخادم. يلزم وصول معتمد للإفصاحات؛ لا يجري تجاوز الحجب.",
  },
  {
    id: "spa",
    name: "وكالة الأنباء السعودية",
    url: "https://www.spa.gov.sa/",
    type: "official",
    note: "الموقع متاح، لكن الشروط تقصر إعادة نشر المحتوى على الاستخدام الشخصي غير التجاري؛ لم يُفعّل الربط دون إذن الوكالة.",
  },
  {
    id: "stats",
    name: "الهيئة العامة للإحصاء",
    url: "https://www.stats.gov.sa/",
    type: "official",
    note: "غير مربوط؛ فشل اتصال الخادم بالموقع أثناء الاختبار. يلزم تغذية رسمية قابلة للوصول.",
  },
  {
    id: "argaam",
    name: "أرقام",
    url: "https://www.argaam.com/",
    type: "media",
    note: "الصفحة العامة متاحة، لكن خريطة الأخبار المعلنة أعادت HTML بدل XML وروابط المحتوى تحمل قفل اشتراك؛ يلزم مصدر محتوى مرخّص. لم يُفعّل ربط صوري.",
  },
  {
    id: "asharq",
    name: "الشرق للأعمال",
    url: "https://asharqbusiness.com/",
    type: "media",
    note: "غير مربوط؛ أعاد الموقع HTTP 403. يلزم تغذية مصرح بها أو اتفاق وصول؛ لم تُتجاوز القيود.",
  },
  {
    id: "cnbcarabia",
    name: "سي إن بي سي عربية",
    url: "https://www.cnbcarabia.com/",
    type: "media",
    note: "غير مربوط؛ الصفحة المتاحة هي غلاف JavaScript بلا أخبار قابلة للتحليل، ولم يُعثر على تغذية عامة موثقة.",
  },
  {
    id: "reuters",
    name: "رويترز",
    url: "https://www.reuters.com/",
    type: "media",
    note: "غير متصل؛ يتطلب ربط المحتوى اتفاق وصول مع المزود.",
  },
  {
    id: "bloomberg",
    name: "بلومبرغ",
    url: "https://www.bloomberg.com/",
    type: "media",
    note: "غير متصل؛ يتطلب وصولًا مرخصًا من المزود.",
  },
  {
    id: "maaal",
    name: "صحيفة مال",
    url: "https://maaal.com/",
    type: "media",
    note: "غير مربوط؛ الموقع وسياسة robots.txt أعادا حجب Cloudflare برمز 403. يلزم وصول مصرح به.",
  },
  {
    id: "sabq",
    name: "سبق",
    url: "https://sabq.org/",
    type: "media",
    note: "رابط مرجعي فقط.",
  },
  {
    id: "mediatameen",
    name: "ميديا تأمين",
    url: "https://www.mediatameen.com/",
    type: "media",
    note: "رابط مرجعي من الدليل السابق؛ غير متصل آليًا.",
  },
  {
    id: "alarabiya",
    name: "العربية",
    url: "https://www.alarabiya.net/",
    type: "media",
    note: "غير مربوط؛ قسم الأسواق أعاد HTTP 403 من الخادم؛ يلزم رابط تغذية أو وصول معتمد.",
  },
  {
    id: "ekhbariya",
    name: "الإخبارية",
    url: "https://www.ekhbariyatv.sa/",
    type: "media",
    note: "غير مربوط؛ فشل الاتصال بالعنوان المسجل أثناء الاختبار. يلزم رابط حالي لتغذية رسمية.",
  },
  {
    id: "jazeera",
    name: "الجزيرة",
    url: "https://www.aljazeera.net/",
    type: "media",
    note: "توجد RSS، لكن سياسة الموقع تمنع الجمع الآلي والتخزين والاستخدام التجاري دون إذن مكتوب؛ لم يُفعّل الربط.",
  },
  {
    id: "aawsat",
    name: "الشرق الأوسط",
    url: "https://aawsat.com/",
    type: "media",
    connector: "news-sitemap",
    feedUrl: "https://aawsat.com/googlenews.xml",
    newsPath: "/الاقتصاد/",
    note: "عناوين وروابط وتواريخ النشر من خريطة الأخبار المعلنة في robots.txt؛ لا يُنسخ نص المقال.",
  },
  {
    id: "aleqt",
    name: "الاقتصادية",
    url: "https://www.aleqt.com/",
    type: "media",
    connector: "news-sitemap",
    feedUrl: "https://www.aleqt.com/sitemaps/newsSitemap.xml",
    note: "بيانات الأخبار الاقتصادية من خريطة الأخبار الرسمية؛ العنوان والرابط وتاريخ النشر فقط.",
  },
  {
    id: "arabnews",
    name: "عرب نيوز",
    url: "https://www.arabnews.com/",
    type: "media",
    connector: "rss",
    feedUrl: "https://www.arabnews.com/rss.xml",
    language: "en",
    note: "تغذية RSS المنشورة بالموقع؛ الأخبار الاقتصادية ذات الصلة. العناوين الأصلية الإنجليزية موسومة بوضوح.",
  },
  {
    id: "ft",
    name: "فايننشال تايمز",
    url: "https://www.ft.com/",
    type: "media",
    note: "دليل فقط؛ محتوى خاضع للاشتراك.",
  },
  {
    id: "wsj",
    name: "وول ستريت جورنال",
    url: "https://www.wsj.com/",
    type: "media",
    note: "دليل فقط؛ محتوى خاضع للاشتراك.",
  },
  {
    id: "cnbc",
    name: "سي إن بي سي",
    url: "https://www.cnbc.com/",
    type: "media",
    note: "رابط مرجعي فقط.",
  },
  {
    id: "investing",
    name: "إنفستنج",
    url: "https://www.investing.com/",
    type: "media",
    note: "دليل فقط؛ الأسعار غير مربوطة.",
  },
  ...[
    ["SaudiExchange", "تداول السعودية"],
    ["argaamplus", "أرقام بلس"],
    ["SAMA_Gov", "البنك المركزي السعودي"],
    ["CMA_Gov", "هيئة السوق المالية"],
    ["Reuters", "رويترز"],
    ["business", "بلومبرغ"],
  ].map(([id, name]): Source => ({
    id: `x-${id}`,
    name: `${name} · إكس`,
    url: `https://x.com/${id}`,
    type: "social",
    note: "حساب مرجعي؛ لا يُستخدم منفردًا لإثبات الأخبار أو الأرقام.",
  })),
];
