import type { Source } from "./types";
export const REFRESH_MINUTES = 15;
export const sources: Source[] = [
  {
    id: "ia",
    name: "هيئة التأمين",
    url: "https://www.ia.gov.sa/ar/home",
    type: "official",
    connector: "ia",
    note: "قراءة الصفحة العامة للأخبار؛ مع احترام سياسة الوصول.",
  },
  {
    id: "cma",
    name: "هيئة السوق المالية",
    url: "https://cma.gov.sa/MediaCenter/NEWS/Pages/default.aspx",
    type: "official",
    connector: "cma",
    note: "الأخبار والإعلانات الرسمية المنشورة للعامة.",
  },
  {
    id: "najm",
    name: "نجم لخدمات التأمين",
    url: "https://najm.sa/",
    type: "official",
    note: "دليل فقط؛ لم تُربط تغذية آلية موثقة.",
  },
  {
    id: "sama",
    name: "البنك المركزي السعودي",
    url: "https://www.sama.gov.sa/",
    type: "official",
    note: "دليل فقط؛ تعذر جلب صفحة الأخبار من الخادم عند الاختبار.",
  },
  {
    id: "exchange",
    name: "تداول السعودية",
    url: "https://www.saudiexchange.sa/",
    type: "official",
    note: "دليل الإفصاحات؛ يلزم مصدر بيانات مرخص لربط الأسعار والنتائج آليًا.",
  },
  {
    id: "spa",
    name: "وكالة الأنباء السعودية",
    url: "https://www.spa.gov.sa/",
    type: "official",
    note: "دليل فقط؛ لم يُربط وصول برمجي موثق.",
  },
  {
    id: "stats",
    name: "الهيئة العامة للإحصاء",
    url: "https://www.stats.gov.sa/",
    type: "official",
    note: "المرجع الرسمي للنشرات الإحصائية؛ غير متصل آليًا.",
  },
  {
    id: "argaam",
    name: "أرقام",
    url: "https://www.argaam.com/",
    type: "media",
    note: "دليل فقط؛ بيانات الواجهة البرمجية خاضعة لاتفاق وترخيص المزود.",
  },
  {
    id: "asharq",
    name: "الشرق للأعمال",
    url: "https://asharqbusiness.com/",
    type: "media",
    note: "دليل فقط؛ لا يجري تجاوز قيود الوصول أو الاشتراك.",
  },
  {
    id: "cnbcarabia",
    name: "سي إن بي سي عربية",
    url: "https://www.cnbcarabia.com/",
    type: "media",
    note: "دليل فقط؛ غير متصل بتغذية آلية.",
  },
  {
    id: "reuters",
    name: "رويترز",
    url: "https://www.reuters.com/",
    type: "media",
    note: "غير متصل؛ يتطلب ربط المحتوى اتفاق وصول مع المزود.",
  },
  {
    id: "bloomberg",
    name: "بلومبرغ",
    url: "https://www.bloomberg.com/",
    type: "media",
    note: "غير متصل؛ يتطلب وصولًا مرخصًا من المزود.",
  },
  {
    id: "maaal",
    name: "صحيفة مال",
    url: "https://maaal.com/",
    type: "media",
    note: "رابط مرجعي فقط.",
  },
  {
    id: "sabq",
    name: "سبق",
    url: "https://sabq.org/",
    type: "media",
    note: "رابط مرجعي فقط.",
  },
  {
    id: "mediatameen",
    name: "ميديا تأمين",
    url: "https://www.mediatameen.com/",
    type: "media",
    note: "رابط مرجعي من الدليل السابق؛ غير متصل آليًا.",
  },
  {
    id: "alarabiya",
    name: "العربية",
    url: "https://www.alarabiya.net/",
    type: "media",
    note: "رابط مرجعي فقط.",
  },
  {
    id: "ekhbariya",
    name: "الإخبارية",
    url: "https://www.ekhbariyatv.sa/",
    type: "media",
    note: "رابط مرجعي فقط.",
  },
  {
    id: "jazeera",
    name: "الجزيرة",
    url: "https://www.aljazeera.net/",
    type: "media",
    note: "رابط مرجعي فقط.",
  },
  {
    id: "aawsat",
    name: "الشرق الأوسط",
    url: "https://aawsat.com/",
    type: "media",
    note: "رابط مرجعي فقط.",
  },
  {
    id: "ft",
    name: "فايننشال تايمز",
    url: "https://www.ft.com/",
    type: "media",
    note: "دليل فقط؛ محتوى خاضع للاشتراك.",
  },
  {
    id: "wsj",
    name: "وول ستريت جورنال",
    url: "https://www.wsj.com/",
    type: "media",
    note: "دليل فقط؛ محتوى خاضع للاشتراك.",
  },
  {
    id: "cnbc",
    name: "سي إن بي سي",
    url: "https://www.cnbc.com/",
    type: "media",
    note: "رابط مرجعي فقط.",
  },
  {
    id: "investing",
    name: "إنفستنج",
    url: "https://www.investing.com/",
    type: "media",
    note: "دليل فقط؛ الأسعار غير مربوطة.",
  },
  ...[
    ["SaudiExchange", "تداول السعودية"],
    ["argaamplus", "أرقام بلس"],
    ["SAMA_Gov", "البنك المركزي السعودي"],
    ["CMA_Gov", "هيئة السوق المالية"],
    ["Reuters", "رويترز"],
    ["business", "بلومبرغ"],
  ].map(([id, name]): Source => ({
    id: `x-${id}`,
    name: `${name} · إكس`,
    url: `https://x.com/${id}`,
    type: "social",
    note: "حساب مرجعي؛ لا يُستخدم منفردًا لإثبات الأخبار أو الأرقام.",
  })),
];
